/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package anagrafescolastica;

import java.util.*;
import javax.swing.table.*;

/**
 *
 * @author tadde
 */
public class AnagrafeGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AnagrafeGUI.class.getName());
    private Anagrafe a;
    private GestioneFile gF;
    private DefaultTableModel model = new DefaultTableModel(new String[]{"Matricola", "Nome", "Cognome"}, 18);
    
    /**
     * Creates new form AnagrafeGUI
     */
    public AnagrafeGUI() {
        initComponents();
        a = new Anagrafe();
        gF = new GestioneFile();
        tblAnagrafe.setSize(pnlAnagrafe.getWidth(), pnlAnagrafe.getHeight());
        tblAnagrafe.setModel(model);
    }

    public void aggiornaAnagrafe() { 
        model.setRowCount(0);
        for (Studente s : a.getListaStudenti()) {
            model.addRow(new Object[]{s.getMatricola(), s.getNome(), s.getCognome()});
        }
    }
    
    public void rimuoviStudente() {
        int rS = tblAnagrafe.getSelectedRow();
        if (rS != -1) {
            model.removeRow(rS);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitolo = new javax.swing.JPanel();
        lblTitolo = new javax.swing.JLabel();
        pnlAnagrafe = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnagrafe = new javax.swing.JTable();
        pnlBottoni = new javax.swing.JPanel();
        btnAggiungi = new javax.swing.JButton();
        btnRimuovi = new javax.swing.JButton();
        btnCerca = new javax.swing.JButton();
        btnCarica = new javax.swing.JButton();
        btnSalva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Anagrafe Scolastica");

        pnlTitolo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlTitolo.setLayout(new java.awt.BorderLayout());

        lblTitolo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitolo.setText("Anagrafe Scolastica");
        pnlTitolo.add(lblTitolo, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlTitolo, java.awt.BorderLayout.PAGE_START);

        pnlAnagrafe.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista Studenti", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        pnlAnagrafe.setPreferredSize(new java.awt.Dimension(300, 348));
        pnlAnagrafe.setLayout(new java.awt.BorderLayout());

        tblAnagrafe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAnagrafe);

        pnlAnagrafe.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlAnagrafe, java.awt.BorderLayout.LINE_START);

        pnlBottoni.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        btnAggiungi.setText("Aggiungi Studente");
        btnAggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggiungiActionPerformed(evt);
            }
        });

        btnRimuovi.setText("Rimuovi Studente");
        btnRimuovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRimuoviActionPerformed(evt);
            }
        });

        btnCerca.setText("Cerca Studente");
        btnCerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCercaActionPerformed(evt);
            }
        });

        btnCarica.setText("Carica File");
        btnCarica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaricaActionPerformed(evt);
            }
        });

        btnSalva.setText("Salva File");
        btnSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBottoniLayout = new javax.swing.GroupLayout(pnlBottoni);
        pnlBottoni.setLayout(pnlBottoniLayout);
        pnlBottoniLayout.setHorizontalGroup(
            pnlBottoniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottoniLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBottoniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRimuovi, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerca, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarica, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalva, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAggiungi, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlBottoniLayout.setVerticalGroup(
            pnlBottoniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottoniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAggiungi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRimuovi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerca, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCarica, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalva, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pnlBottoni, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggiungiActionPerformed
        InputStudente iS = new InputStudente(this, true);
        iS.setLocationRelativeTo(null);
        iS.setVisible(true);
        
        String matricola = iS.getMatricola();
        String nome = iS.getNome();
        String cognome = iS.getCognome();
        
        a.aggiungiStudente(new Studente(matricola, nome, cognome));
        
        aggiornaAnagrafe();
    }//GEN-LAST:event_btnAggiungiActionPerformed

    private void btnRimuoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRimuoviActionPerformed
        rimuoviStudente();
    }//GEN-LAST:event_btnRimuoviActionPerformed

    private void btnCercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCercaActionPerformed
        
    }//GEN-LAST:event_btnCercaActionPerformed

    private void btnCaricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaricaActionPerformed
        SceltaFile sF = new SceltaFile(this, true);
        sF.setLocationRelativeTo(null);
        sF.setVisible(true);
        
        a.svuota();
        
        ArrayList<Studente> studentiFile = gF.caricaDaFile(sF.getFile());
        for (Studente s : studentiFile) {
            a.aggiungiStudente(s);
        }
        aggiornaAnagrafe();
    }//GEN-LAST:event_btnCaricaActionPerformed

    private void btnSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvaActionPerformed
        gF.salvaSuFile("testo.txt", a.getTuttiStudenti());
    }//GEN-LAST:event_btnSalvaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAggiungi;
    private javax.swing.JButton btnCarica;
    private javax.swing.JButton btnCerca;
    private javax.swing.JButton btnRimuovi;
    private javax.swing.JButton btnSalva;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JPanel pnlAnagrafe;
    private javax.swing.JPanel pnlBottoni;
    private javax.swing.JPanel pnlTitolo;
    private javax.swing.JTable tblAnagrafe;
    // End of variables declaration//GEN-END:variables
}
