/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package anagrafescolastica;

/**
 *
 * @author taboada.taddeo
 */
public class CercaStudente extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CercaStudente.class.getName());
    private String matricola;

    /**
     * Creates new form CercaStudente
     */
    public CercaStudente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitolo = new javax.swing.JPanel();
        lblTitolo = new javax.swing.JLabel();
        pnlInput = new javax.swing.JPanel();
        lblMatricola = new javax.swing.JLabel();
        txtMatricola = new javax.swing.JTextField();
        pnlConferma = new javax.swing.JPanel();
        btnConferma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cerca Studente");

        pnlTitolo.setBackground(new java.awt.Color(0, 204, 204));
        pnlTitolo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlTitolo.setLayout(new java.awt.BorderLayout());

        lblTitolo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitolo.setText("Cerca Studente");
        pnlTitolo.add(lblTitolo, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlTitolo, java.awt.BorderLayout.PAGE_START);

        pnlInput.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlInput.setPreferredSize(new java.awt.Dimension(400, 100));
        pnlInput.setLayout(new java.awt.GridLayout(1, 2, 10, 10));

        lblMatricola.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMatricola.setText("Matricola:");
        pnlInput.add(lblMatricola);

        txtMatricola.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pnlInput.add(txtMatricola);

        getContentPane().add(pnlInput, java.awt.BorderLayout.CENTER);

        pnlConferma.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlConferma.setLayout(new java.awt.BorderLayout());

        btnConferma.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnConferma.setText("Conferma");
        btnConferma.setToolTipText("");
        btnConferma.setPreferredSize(new java.awt.Dimension(75, 50));
        btnConferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfermaActionPerformed(evt);
            }
        });
        pnlConferma.add(btnConferma, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlConferma, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfermaActionPerformed
        matricola = txtMatricola.getText();
        dispose();
    }//GEN-LAST:event_btnConfermaActionPerformed

    public String getMatricola() {
        return matricola;
    }  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConferma;
    private javax.swing.JLabel lblMatricola;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JPanel pnlConferma;
    private javax.swing.JPanel pnlInput;
    private javax.swing.JPanel pnlTitolo;
    private javax.swing.JTextField txtMatricola;
    // End of variables declaration//GEN-END:variables
}
