/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package anagrafescolastica;

/**
 *
 * @author taboada.taddeo
 */
public class InputStudente extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InputStudente.class.getName());
    private String matricola, nome, cognome;

    /**
     * Creates new form InputStudente
     */
    public InputStudente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlConferma = new javax.swing.JPanel();
        btnConferma = new javax.swing.JButton();
        pnlTitolo = new javax.swing.JPanel();
        lblTitolo = new javax.swing.JLabel();
        pnlInput = new javax.swing.JPanel();
        lblMatricola = new javax.swing.JLabel();
        txtMatricola = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCognome = new javax.swing.JLabel();
        txtCognome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlConferma.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlConferma.setPreferredSize(new java.awt.Dimension(400, 75));
        pnlConferma.setLayout(new java.awt.BorderLayout());

        btnConferma.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnConferma.setText("Conferma");
        btnConferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfermaActionPerformed(evt);
            }
        });
        pnlConferma.add(btnConferma, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlConferma, java.awt.BorderLayout.PAGE_END);

        pnlTitolo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlTitolo.setLayout(new java.awt.BorderLayout());

        lblTitolo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitolo.setText("Inserisci Studente");
        pnlTitolo.add(lblTitolo, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlTitolo, java.awt.BorderLayout.PAGE_START);

        pnlInput.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlInput.setLayout(new java.awt.GridLayout(3, 2, 10, 10));

        lblMatricola.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMatricola.setText("Matricola:");
        pnlInput.add(lblMatricola);

        txtMatricola.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pnlInput.add(txtMatricola);

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNome.setText("Nome:");
        pnlInput.add(lblNome);

        txtNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pnlInput.add(txtNome);

        lblCognome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCognome.setText("Cognome:");
        pnlInput.add(lblCognome);

        txtCognome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pnlInput.add(txtCognome);

        getContentPane().add(pnlInput, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfermaActionPerformed
        matricola = txtMatricola.getText();
        nome = txtNome.getText();
        cognome = txtCognome.getText();
        dispose();
    }//GEN-LAST:event_btnConfermaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                InputStudente dialog = new InputStudente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public String getMatricola() {
        return matricola;
    }

    public String getNome() {
        return nome;
    }

    public String getCognome() {
        return cognome;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConferma;
    private javax.swing.JLabel lblCognome;
    private javax.swing.JLabel lblMatricola;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JPanel pnlConferma;
    private javax.swing.JPanel pnlInput;
    private javax.swing.JPanel pnlTitolo;
    private javax.swing.JTextField txtCognome;
    private javax.swing.JTextField txtMatricola;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
